### ISSUE TITLE
Allow usage through Spec() method in addition to string extension method

### ISSUE THREAD

**Issue by asbjornu** [bbvch/LambdaTale#30]
I like what this library does, I'm just not a fan of the extension method `x()` as the way to consume its functionality.

I've quickly written up a way to describe tests with a `Test()` method that basically does exactly the same as the `x()` extension method does, however in a way that feels more natural and idiomatic C# and also more familiar to developers coming from BDD-style test frameworks in other languages, such as Jest, Jasmine, Mocha, RSpec, Go test, etc.

From the consuming side, it would look something like this:

```cs
public class SpecFeature : Spec
{
    [Scenario]
    public void Spec()
    {
        Test("Async works", async () =>
        {
            await Task.Delay(1);
            Assert.True(true);
        });

        Test("Sync works", () =>
        {
            Assert.True(true);
        });
    }
}
```

And the `Spec` implementation is as simple as this:

```cs
public abstract class Spec
{
    protected IStepDefinition Test(string text, Func<Task> body)
    {
        var stepDefinition = new StepDefinition
        {
            Text = text,
            Body = body == null ? null : _ => body()
        };

        CurrentThread.Add(stepDefinition);
        return stepDefinition;
    }

    protected IStepDefinition Test(string text, Action body)
    {
        var stepDefinition = new StepDefinition
        {
            Text = text,
            Body = body == null ? null : _ =>
            {
                body();
                return Task.CompletedTask;
            }
        };

        CurrentThread.Add(stepDefinition);
        return stepDefinition;
    }
}
```

With C# 6.0 static imports, it would be possible to define the `Test()` method statically instead, if you prefer that. It would also be possible to pass the `Spec` class into the `[Scenario]` method. The names `Spec` and `Test` are of course up for discussion.

What do you think? Is this something that could become a part of LambdaTale? If so, I would be happy to submit a PR. I would also love to discuss the possibility of adding support for nesting of these `Test()` methods.

**Comment by CaringDev** [comment]
Sorry for the late reply... I'm currently "out of office" for my honemoon 🤩
I like the idea of having a static `Test` method, forcing specs to inherit from a base class not so much. As for the naming... I've no better idea, so `Test` is fine for me :-D
If you could also add nesting, that would be great! I'd like to keep the PRs separate though, if possible.

**Comment by asbjornu** [comment]
@CaringDev Congratulations! 🎉 Sounds good! I've started refactoring towards a static `Test` method, but quickly hit a wall because of a collision with `namespace LambdaTale.Test`. Do you prefer a rename of the namespace to `LambdaTale.Tests` or of the method from `Test()` to `Spec()` or something similar, perhaps more collision-safe?

**Comment by CaringDev** [comment]
> I've started refactoring towards a static `Test` method

Cool, thanks!

> a collision with `namespace LambdaTale.Test`. Do you prefer a rename of the namespace and assembly to `LambdaTale.Tests` (plural) or of the static method from `Test()` to `Spec()` or something similar, perhaps more collision-safe?

I'd go for `Spec("the thing")` then. We might eventually regret but this seems to be a good solution now.

**Comment by asbjornu** [comment]
I've submitted #33 to implement the static `Spec()` method. Now I'd like to move on to implementing nesting. Any idea how to accomplish that?

**Comment by iamkoch** [comment]
Is there scope to alias `Test` to `Given`, `When`, `Then` and `And`? They're syntactic sugar but (I imagine) fit a large proportion of tests written using the framework.

**Comment by asbjornu** [comment]
@iamkoch, sure. Should be easy enough for me to add to #33 if @CaringDev agrees to it.

**Comment by CaringDev** [comment]
> Is there scope to alias `Test` to `Given`, `When`, `Then` and `And`? They're syntactic sugar but (I imagine) fit a large proportion of tests written using the framework.

Personally I'd rather not 'pollute' the library too much... @iamkoch could you elaborate more in #37 on the envisioned use cases?
